# Setup
title:               kevanchristmas.io
tagline:             'A memex/zettelkasten'
description:         'What it says in the first post'
url:                 http://kevanchristmas.GitHub.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kevan Christmas
  url:               https://someurl
  email:             kevan@the10x.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
